[package]
edition = "2021"
name = "textalyzer-wasm"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json = "1.0.114"
textalyzer = {path = "../textalyzer"}
wasm-bindgen = "0.2.92"
