model: openai/o3
architect: true

# model: gemini/gemini-2.5-pro

auto-test: true
test-cmd: cargo test

# auto-lint: true
# lint-cmd: cargo fmt

auto-commits: false
attribute-committer: false

file:
  - Cargo.toml
  - textalyzer-wasm/src/lib.rs
  - textalyzer/src/duplication.rs
  - textalyzer/src/file_utils.rs
  - textalyzer/src/frequency.rs
  - textalyzer/src/lib.rs
  - textalyzer/src/line_length.rs
  - textalyzer/src/main.rs
  - textalyzer/src/output.rs
  - textalyzer/src/types.rs

read:
  - textalyzer/tests/integration_tests.rs
